language: java

jdk:
  - oraclejdk8

before_deploy:
  - "mvn versions:set -DnewVersion=$TRAVIS_TAG"
  - "mvn -DskipTests package install"

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - "$TRAVIS_BUILD_DIR/target/minimesos-maven-plugin-$TRAVIS_TAG.jar"
    - "$TRAVIS_BUILD_DIR/target/minimesos-maven-plugin-$TRAVIS_TAG.pom"
  skip_cleanup: true
  on:
    tags: true