language: java

jdk:
  - oraclejdk8

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - "/home/travis/.m2/repository/com/containersolutions/minimesos/minimesos-maven-plugin/$TRAVIS_TAG/minimesos-maven-plugin-$TRAVIS_TAG.jar"
    - "/home/travis/.m2/repository/com/containersolutions/minimesos/minimesos-maven-plugin/$TRAVIS_TAG/minimesos-maven-plugin-$TRAVIS_TAG.pom"
  skip_cleanup: true
  on:
    tags: true