language: java

jdk:
  - oraclejdk8

before_deploy:
  - "mvn versions:set -DnewVersion=$TRAVIS_TAG"
  - "mvn -DskipTests package install"

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - "/home/travis/.m2/repository/com/github/ContainerSolutions/minimesos-maven-plugin/$TRAVIS_TAG/minimesos-maven-plugin-$TRAVIS_TAG.jar"
    - "/home/travis/.m2/repository/com/github/ContainerSolutions/minimesos-maven-plugin/$TRAVIS_TAG/minimesos-maven-plugin-$TRAVIS_TAG.pom"
  skip_cleanup: true
  on:
    tags: true